### ISSUE TITLE
cannot access plugin?

### ISSUE THREAD

**Issue by hilasharim** [bionanogenomics/JBrowsePlugin#6]
I've followed the instructions on the installation page and I am now trying to upload data. The usage instructions page says:
"(2) Under the File heading on your menu you should see a 'Add BioNanoGenomics Map file' option "

However, our JBrowse instance looks like this:
![image](https://cloud.githubusercontent.com/assets/20622004/17082545/1eee40b6-518b-11e6-914c-c13a3377c9ca.png)

and there is no File heading. The plugin doesn't appear in any of the headings we have.
Is there something else that we need to configure?

Thanks,
Hila

**Comment by cmdcolin** [comment]
You can get back the "File" menu by adding classicMenu=true to jbrowse.conf. That is an option added in JBrowse 1.12.0+ to change the "Genome" and "Track" menus back to just say "File"

**Comment by hilasharim** [comment]
I un-commented the line classicMenu = true in jbrowse.conf - the browser still looks the same (no "File" menu).

Are there any other changes that need to be made?

**Comment by hilasharim** [comment]
It shows up now. Thanks

**Comment by conniecl** [comment]
@hilasharim  hi, i also face the same problem as you, how you shows up the "file" menu? I restart my Jbrowse, but nothing works. Sincerely hope can get your advise, even though it has been a long time.
